"""update role table

Revision ID: 21f71e1435d5
Revises: 7b0189b62aa5
Create Date: 2024-06-16 16:44:48.620851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '21f71e1435d5'
down_revision: Union[str, None] = '7b0189b62aa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('label', sa.String(length=200), nullable=False))
    op.alter_column('roles', 'name',
               existing_type=mysql.ENUM('user', 'admin', 'super'),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.create_index(op.f('ix_roles_label'), 'roles', ['label'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_label'), table_name='roles')
    op.alter_column('roles', 'name',
               existing_type=sa.String(length=200),
               type_=mysql.ENUM('user', 'admin', 'super'),
               existing_nullable=False)
    op.drop_column('roles', 'label')
    # ### end Alembic commands ###
