"""add tokens table

Revision ID: 541bcadb5771
Revises: 178c07571429
Create Date: 2024-06-16 17:03:53.131729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541bcadb5771'
down_revision: Union[str, None] = '178c07571429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('expires', sa.DateTime(), nullable=False, comment='The expiration time.'),
    sa.Column('created', sa.DateTime(), nullable=False, comment='The creation time'),
    sa.Column('ip', sa.String(length=45), nullable=False, comment='The IP address'),
    sa.Column('user_agent', sa.String(length=250), nullable=False, comment='The user agent string'),
    sa.Column('desc', sa.String(length=250), nullable=True, comment='A description'),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tokens_id'), 'tokens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_id'), table_name='tokens')
    op.drop_table('tokens')
    # ### end Alembic commands ###
